### ISSUE TITLE
Can't install in windows 

### ISSUE THREAD

**Issue by Kayro11** [jinjamator/pyperf2#2]
Can't install in windows ,because pyjq is not work well:
`Installing collected packages: win-inet-pton, pyjq, pyroute2, pyperf2
  Running setup.py install for pyjq ... error
  error: subprocess-exited-with-error

  × Running setup.py install for pyjq did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.9
      copying pyjq.py -> build\lib.win-amd64-3.9
      running build_ext
      RefactoringTool: Refactored C:\Users\kayro\AppData\Local\Temp\pip-install-xsqkx9_j\pyjq_082081dff55d4e96ae9d530c553df93b\dependencies\onig-6.9.0\src\gperf_fold_key_conv.py
      RefactoringTool: Files that were modified:
      RefactoringTool: C:\Users\kayro\AppData\Local\Temp\pip-install-xsqkx9_j\pyjq_082081dff55d4e96ae9d530c553df93b\dependencies\onig-6.9.0\src\gperf_fold_key_conv.py
      RefactoringTool: Refactored C:\Users\kayro\AppData\Local\Temp\pip-install-xsqkx9_j\pyjq_082081dff55d4e96ae9d530c553df93b\dependencies\onig-6.9.0\src\gperf_unfold_key_conv.py
      RefactoringTool: Files that were modified:
      RefactoringTool: C:\Users\kayro\AppData\Local\Temp\pip-install-xsqkx9_j\pyjq_082081dff55d4e96ae9d530c553df93b\dependencies\onig-6.9.0\src\gperf_unfold_key_conv.py
      RefactoringTool: Refactored C:\Users\kayro\AppData\Local\Temp\pip-install-xsqkx9_j\pyjq_082081dff55d4e96ae9d530c553df93b\dependencies\onig-6.9.0\src\make_unicode_egcb_data.py
      RefactoringTool: Files that were modified:
      RefactoringTool: C:\Users\kayro\AppData\Local\Temp\pip-install-xsqkx9_j\pyjq_082081dff55d4e96ae9d530c553df93b\dependencies\onig-6.9.0\src\make_unicode_egcb_data.py
      RefactoringTool: Refactored C:\Users\kayro\AppData\Local\Temp\pip-install-xsqkx9_j\pyjq_082081dff55d4e96ae9d530c553df93b\dependencies\onig-6.9.0\src\make_unicode_fold_data.py
      RefactoringTool: Files that were modified:
      RefactoringTool: C:\Users\kayro\AppData\Local\Temp\pip-install-xsqkx9_j\pyjq_082081dff55d4e96ae9d530c553df93b\dependencies\onig-6.9.0\src\make_unicode_fold_data.py
      RefactoringTool: Refactored C:\Users\kayro\AppData\Local\Temp\pip-install-xsqkx9_j\pyjq_082081dff55d4e96ae9d530c553df93b\dependencies\onig-6.9.0\src\make_unicode_property_data.py
      RefactoringTool: Files that were modified:
      RefactoringTool: C:\Users\kayro\AppData\Local\Temp\pip-install-xsqkx9_j\pyjq_082081dff55d4e96ae9d530c553df93b\dependencies\onig-6.9.0\src\make_unicode_property_data.py
      error: [WinError 2] 系统找不到指定的文件。
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pyjq

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.`

**Comment by jinjamator** [comment]
This is not a real issue, because Windows is not a supported platform. Pyperf2 relates on the Linux netlink interface to configure networking. 
I'll update the documentation to make it clear that this a Linux only software.
